Homework4
EleKon612/ElenaKonovalova_LevelUp pull request #10
Opened 2022-06-28 15:45 UTC by EleKon612

Как и писала в чате, тесты периодически падают совершенно в разных местах, хотя везде стоит wait.until visibility/element to be clickable, пришлось добавить implicit wait (до этого был только explicit), стало лучше, но неидеально. Я уже не знаю как достичь 100% проходимости, прошу помочь, если есть идеи, как можно улучшить, или принять так

2022-06-29 15:48 UTC, khda91 requested changes
![image](https://user-images.githubusercontent.com/7585107/176477942-1a8e646e-ab45-4a98-8c45-f86664fda097.png)

Очень много лишних файлов, которые не относятся к pull request
1. Сделать rebase на main ветку и запушить
2. Проверить, что в PR только файлы, которые относятся к домашней работе
3. Исправить замечания к работе

2022-06-29 15:48 UTC, khda91 commented on src/main/java/ru/levelp/at/lesson0507/selenium/page/objects/homework4/Homework4RefactorBasePage.java
> +    protected final String testFolderURL = "https://e.mail.ru/1/";
За чем нужны эти ссылки?

2022-06-29 15:48 UTC, khda91 commented on src/main/java/ru/levelp/at/lesson0507/selenium/page/objects/homework4/Homework4RefactorBasePage.java
> +    protected final String subject3 = "This is a perfect letter";
Тестовые данные не должны храниться на уровне Page Objects

2022-06-29 15:48 UTC, khda91 commented on src/main/java/ru/levelp/at/lesson0507/selenium/page/objects/homework4/Homework4RefactorMethodsAndElements.java
> +public class Homework4RefactorMethodsAndElements extends Homework4RefactorBasePage {
нужно разбить на Page Objects. Почта не одностраничное приложение, которое можно описать с помощью одного класса. 
В этой работе как минимум должно быть 3 класса
* класс базовой страницы
* класс главной страницы mail.ru
* класс страницы с почтой

2022-06-29 15:48 UTC, khda91 commented on src/main/java/ru/levelp/at/lesson0507/selenium/page/objects/homework4/Homework4RefactorMethodsAndElements.java
> +    private WebElement trashBinPage;
Группу всех этих элементов можно собрать в `List<WebElement>` и написать метод, который будет циклом пробегаться по всем элементам и кликать по нужному. Чтобы определить нужны на вход можно подавать имя папки, куда хотим перейти

2022-06-29 15:48 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/pageobjects/homework4/Homework4RefactorBaseTest.java
> +    protected final String password = "Selenium2022";
Тестовые данные такие как креды пользователя, должны храниться в properties файле согласно заданию

2022-07-04 22:35 UTC, EleKon612 commented
@khda91 Я исправила все, что было указано в комментариях:
1. Сделать rebase на main ветку и запушила
2. Разбила Page Objects на 3 класса
3. Создала файл properties (+ConfProperties для его прочтения)
4. Перенесла в Properties все ссылки на папки mailru
5. Избавилась от переменных в файлах Page Objects (папки src/main/java)
6. Единственное, что попробовала, но не полуучилось сделать это "Группу всех этих элементов можно собрать в List<WebElement> и написать метод, который будет циклом пробегаться по всем элементам и кликать по нужному. Чтобы определить нужны на вход можно подавать имя папки, куда хотим перейти". Но зато получилось создать список вэб элементов и метод, его использующий, для Exercise1 (для ожидания и подтверждения, что папка "Черновики" пуста)

2022-07-17 20:29 UTC, khda91 approved these changes
Домашняя работа принята

2022-07-17 20:29 UTC, merged