Homework3
EleKon612/ElenaKonovalova_LevelUp pull request #8
Opened 2022-06-21 21:02 UTC by EleKon612

Исправила ошибку с закрытием окна, осталась только 1 ошибка в Exercise1 - из черновиков не исчезает отправленное сообщение, пробовала разные ExpectedConditions, sleepUtils не помогает

2022-06-22 20:38 UTC, khda91 requested changes
1. Очень много лишних файлов, которые не имеют отношения к данной домашней работе
2. checkstyle не прошел
3. Исправить комментарии к работе

![image](https://user-images.githubusercontent.com/7585107/175129390-da3bf932-da4c-42e8-9956-3789831d12af.png)

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +    }
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +    }
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise2MailruTest.java
> +    }
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise2MailruTest.java
> +    }
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise3MailruTest.java
> +
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise3MailruTest.java
> +    }
Вот это всё можно вынести в  базовый класс для selenium тестов

Ровно так же как делали с калькулятором

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +        WebElement enterButton = driver.findElement(By.xpath("//*[contains(@class, 'resplash-btn')]"));
Локатор неплохой, но лучше бы его переписать с использованием атрибута `data-testid`

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +            "//div/iframe[@class='ag-popup__frame__layout__iframe']"));
`div` можно убрать, в целом `iframe` ищется по имени класса и без него

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +        WebElement saveDraft = driver.findElement(By.xpath("//*[text()='Сохранить']"));
На текст лучше бы не завязываться, так как если будет другая локализация тест проходить не будет. 
У данного элемента есть родительский `button` у которого есть атрибут `data-testid`, к которому лучше бы привязаться

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +                .visibilityOfElementLocated(By.xpath("//div[text()='Черновики']")));
Опять же могут возникнуть проблемы с локализацией

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +        // assertFalse(driver.findElement(By.xpath("//span[text()='New TestLetter Subject']")).isDisplayed());
Можно проверить следующим образом:
1. Получить список всех элементов писем
2. Пробежаться по всем элементам и сравинивать текст элементов с нужным

Или же использовать явное ожидание `invisibilityOf`

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise2MailruTest.java
> +    public void exercise2Test() {
Посмотреть комментарии оставленные в `src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java` классе

2022-06-22 20:38 UTC, khda91 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise3MailruTest.java
> +    public void exercise3Test() {
Посмотреть комментарии оставленные в классе `src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java`

2022-06-23 07:59 UTC, EleKon612 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Exercise1MailruTest.java
> +        // assertFalse(driver.findElement(By.xpath("//span[text()='New TestLetter Subject']")).isDisplayed());
@khda91 я нашла в чем проблема с неисчезающим письмом! у меня на закрытие окна после сохранения черновика (вот здесь WebElement closeDraft = driver.findElement(By.xpath("//button[@tabindex='700']"));
        closeDraft.click();) вместо tabindex стоял xpath на class, который был одинаковым для  нескольких кнопок и получается, что письмо не закрывалось, а сворачивалось =) я просто не обращала внимание на одинаковость классов, оказывается надо искать какой-то уникальный элемент

2022-06-24 18:04 UTC, khda91 requested changes
Проект не собирается
Исправить комментарии

![image](https://user-images.githubusercontent.com/7585107/175614911-09e380aa-d3c1-4844-bdaf-12eb15d090aa.png)

2022-06-25 11:48 UTC, EleKon612 commented on src/main/java/ru/levelp/at/lesson0507/selenium/page/objects/voids/UsersBugRedLoginRegistrationPage.java
> +package ru.levelp.at.lesson0507.selenium.page.objects.voids;
удалила уже 2ой раз, я не понимаю откуда они берутся(((

2022-06-25 11:49 UTC, EleKon612 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Homework3SeleniumBaseTest.java
> +    /*@AfterMethod
Аfter method был закомметирован, чтобы при падении тест остановился на этом месте, а не закрывал браузер. Исправила.

2022-06-25 11:51 UTC, EleKon612 commented on src/test/java/ru/levelp/at/lesson0507/selenium/basic/homework3/Homework3SeleniumBaseTest.java
> +    /*@AfterMethod
не понимаю, что значит "не все комментарии исправлены", какие комментарии имеются ввиду? я убрала привязку к тексту элементов папок и тп (кроме получателя, письма и тела письма) и вынесла все в базовый класс

2022-06-29 15:20 UTC, khda91 approved these changes
работа принята

2022-06-29 15:20 UTC, merged